<?php

return [
    [
        'key'    => 'sales.payment_methods.emis_payment',
        'name'   => 'emis-payment::app.admin.system.emis-payment',
        'info'   => 'emis-payment::app.admin.system.emis-payment-info',
        'sort'   => 2,
        'fields' => [
            [
                'name'          => 'active',
                'title'         => 'emis-payment::app.admin.system.status',
                'type'          => 'boolean',
                'default_value' => false,
                'channel_based' => true,
                'validation'    => 'required',
            ],
            [
                'name'          => 'title',
                'title'         => 'emis-payment::app.admin.system.title',
                'type'          => 'text',
                'default_value' => 'EMIS - Multicaixa Express',
                'channel_based' => true,
                'locale_based'  => true,
                'validation'    => 'required',
            ],
            [
                'name'          => 'description',
                'title'         => 'emis-payment::app.admin.system.description',
                'type'          => 'textarea',
                'default_value' => 'Pague com MULTICAIXA Express, QR Code ou Pagar Online.',
                'channel_based' => true,
                'locale_based'  => true,
            ],
            [
                'name'          => 'image',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.logo',
                'type'          => 'image',
                'info'          => 'admin::app.configuration.index.sales.payment-methods.logo-information',
                'depends'       => 'active:1',
                'channel_based' => true,
                'locale_based'  => false,
                'validation'    => 'mimes:bmp,jpeg,jpg,png,webp',
            ],
            [
                'name' => 'callback_url',
                'title' => 'Callback URL',
                'type' => 'blade',
                'path' => 'emis-payment::admin.system.callback-url',
            ],
            [
                'name'       => 'reference_prefix',
                'title'      => 'emis-payment::app.admin.system.reference-prefix',
                'type'       => 'text',
                'validation' => 'required|max:6|alpha_num',
                'info'       => 'emis-payment::app.admin.system.reference-prefix-info',
            ],
            [
                'name'       => 'frame_token',
                'title'      => 'emis-payment::app.admin.system.frame-token',
                'type'       => 'password',
                'validation' => 'required',
                'info'       => 'emis-payment::app.admin.system.frame-token-info',
            ],
            [
                'name'       => 'terminal_id',
                'title'      => 'emis-payment::app.admin.system.terminal-id',
                'type'       => 'text',
                'validation' => 'required',
                'info'       => 'emis-payment::app.admin.system.terminal-id-info',
            ],
            [
                'name'          => 'mobile_mode',
                'title'         => 'emis-payment::app.admin.system.mobile-mode',
                'type'          => 'select',
                'default_value' => 'PAYMENT',
                'validation'    => 'required',
                'options'       => [
                    ['title' => 'PAYMENT', 'value' => 'PAYMENT'],
                    ['title' => 'AUTHORIZATION', 'value' => 'AUTHORIZATION'],
                    ['title' => 'DISABLED', 'value' => 'DISABLED'],
                ],
            ],
            [
                'name'          => 'qrcode_mode',
                'title'         => 'emis-payment::app.admin.system.qrcode-mode',
                'type'          => 'select',
                'default_value' => 'PAYMENT',
                'validation'    => 'required',
                'options'       => [
                    ['title' => 'PAYMENT', 'value' => 'PAYMENT'],
                    ['title' => 'AUTHORIZATION', 'value' => 'AUTHORIZATION'],
                    ['title' => 'DISABLED', 'value' => 'DISABLED'],
                ],
            ],
            [
                'name'          => 'card_mode',
                'title'         => 'emis-payment::app.admin.system.card-mode',
                'type'          => 'select',
                'default_value' => 'DISABLED',
                'validation'    => 'required',
                'info'          => 'emis-payment::app.admin.system.card-mode-info',
                'options'       => [
                    ['title' => 'DISABLED', 'value' => 'DISABLED'],
                    ['title' => 'AUTHORIZATION', 'value' => 'AUTHORIZATION'],
                ],
            ],
            [
                'name'          => 'endpoint',
                'title'         => 'emis-payment::app.admin.system.endpoint',
                'type'          => 'text',
                'default_value' => 'https://pagamentonline.emis.co.ao/online-payment-gateway/portal/frameToken',
                'validation'    => 'required|url',
            ],
            [
                'name'          => 'frame_host',
                'title'         => 'emis-payment::app.admin.system.frame-host',
                'type'          => 'text',
                'default_value' => 'https://pagamentonline.emis.co.ao/online-payment-gateway/portal/frame?token=',
                'validation'    => 'required|url',
            ],
            [
                'name'          => 'sort_order',
                'title'         => 'emis-payment::app.admin.system.sort-order',
                'type'          => 'text',
                'default_value' => 2,
                'validation'    => 'numeric',
            ],
        ],
    ],
];
